/**
 * Plaid API
 * Plaid API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Institution from './Institution';

/**
 * The InstitutionsSearchGet200Response model module.
 * @module model/InstitutionsSearchGet200Response
 * @version 1.0.0
 */
class InstitutionsSearchGet200Response {
    /**
     * Constructs a new <code>InstitutionsSearchGet200Response</code>.
     * @alias module:model/InstitutionsSearchGet200Response
     */
    constructor() { 
        
        InstitutionsSearchGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstitutionsSearchGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstitutionsSearchGet200Response} obj Optional instance to populate.
     * @return {module:model/InstitutionsSearchGet200Response} The populated <code>InstitutionsSearchGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstitutionsSearchGet200Response();

            if (data.hasOwnProperty('institutions')) {
                obj['institutions'] = ApiClient.convertToType(data['institutions'], [Institution]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstitutionsSearchGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstitutionsSearchGet200Response</code>.
     */
    static validateJSON(data) {
        if (data['institutions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['institutions'])) {
                throw new Error("Expected the field `institutions` to be an array in the JSON data but got " + data['institutions']);
            }
            // validate the optional field `institutions` (array)
            for (const item of data['institutions']) {
                Institution.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Institution>} institutions
 */
InstitutionsSearchGet200Response.prototype['institutions'] = undefined;






export default InstitutionsSearchGet200Response;

