/**
 * Plaid API
 * Plaid API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InstitutionsSearchGet200Response from '../model/InstitutionsSearchGet200Response';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the institutionsSearchGet operation.
     * @callback module:api/DefaultApi~institutionsSearchGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InstitutionsSearchGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search institutions
     * Returns a list of institutions matching the search query
     * @param {String} query Search query string
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} [products] Products to filter institutions by
     * @param {module:api/DefaultApi~institutionsSearchGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InstitutionsSearchGet200Response}
     */
    institutionsSearchGet(query, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling institutionsSearchGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'query': query,
        'products': this.apiClient.buildCollectionParam(opts['products'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InstitutionsSearchGet200Response;
      return this.apiClient.callApi(
        '/institutions/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
